### ISSUE TITLE
Permission denied when execute cmd

### ISSUE THREAD

**Issue by pzhangleo** [hiteshsondhi88/ffmpeg-android-java#103]
log is:
05-21 01:15:27.657 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onFinish: load

```
                                                        --------- beginning of system
```

05-21 01:15:41.377 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onStart: process
05-21 01:15:41.387 10181-12305/com.zhp.ffmpegdemo D/FFmpeg: Running publishing updates method
05-21 01:15:41.401 10181-10217/com.zhp.ffmpegdemo W/EGL_emulation: eglSurfaceAttrib not implemented
05-21 01:15:41.401 10181-10217/com.zhp.ffmpegdemo W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xb432cf80, error=EGL_SUCCESS
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress: WARNING: linker: /data/data/com.zhp.ffmpegdemo/files/ffmpeg has text relocations. This is wasting memory and prevents security hardening. Please fix.
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress: ffmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   built with gcc 4.8 (GCC)
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   configuration: --target-os=linux --cross-prefix=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/bin/i686-linux-android- --arch=x86 --cpu=i686 --enable-runtime-cpudetect --sysroot=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/vagrant/SourceCode/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/vagrant/SourceCode/ffmpeg-android/build/x86 --extra-cflags='-I/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -march=i686' --extra-ldflags='-L/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libavutil      55. 17.103 / 55. 17.103
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libavcodec     57. 24.102 / 57. 24.102
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libavformat    57. 25.100 / 57. 25.100
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libavdevice    57.  0.101 / 57.  0.101
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libavfilter     6. 31.100 /  6. 31.100
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libswscale      4.  0.100 /  4.  0.100
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libswresample   2.  0.101 /  2.  0.101
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress:   libpostproc    54.  0.100 / 54.  0.100
05-21 01:15:41.413 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onProgress: /storage/sdcard/input.mp4: Permission denied
05-21 01:15:41.414 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onFailure: WARNING: linker: /data/data/com.zhp.ffmpegdemo/files/ffmpeg has text relocations. This is wasting memory and prevents security hardening. Please fix.
                                                            ffmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
                                                              built with gcc 4.8 (GCC)
                                                              configuration: --target-os=linux --cross-prefix=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/bin/i686-linux-android- --arch=x86 --cpu=i686 --enable-runtime-cpudetect --sysroot=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/vagrant/SourceCode/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/vagrant/SourceCode/ffmpeg-android/build/x86 --extra-cflags='-I/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -march=i686' --extra-ldflags='-L/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
                                                              libavutil      55. 17.103 / 55. 17.103
                                                              libavcodec     57. 24.102 / 57. 24.102
                                                              libavformat    57. 25.100 / 57. 25.100
                                                              libavdevice    57.  0.101 / 57.  0.101
                                                              libavfilter     6. 31.100 /  6. 31.100
                                                              libswscale      4.  0.100 /  4.  0.100
                                                              libswresample   2.  0.101 /  2.  0.101
                                                              libpostproc    54.  0.100 / 54.  0.100
                                                            /storage/sdcard/input.mp4: Permission denied
05-21 01:15:41.414 10181-10181/com.zhp.ffmpegdemo D/ffmpeg: onFinish:

**Comment by prasanthmurugan** [comment]
did you found the solution !! I am facing the same problem now

**Comment by matteinn** [comment]
Did you declare the permissions needed to access the external storage?
If so, then adding the "-safe 0" flag to your ffmpeg command may help

**Comment by prasanthmurugan** [comment]
@matteinn thanks!!That's my mistake i didn't declare permission to access the external storage !!

**Comment by matteinn** [comment]
@prasanthmurugan you're welcome! I guess you can close the issue :)

**Comment by liuxue0905** [comment]
```
-i rtsp://XXX -c:a copy -c:v copy -bsf:a aac_adtstoasc /storage/0123-4567/Download/a.mp4
```

```
ext {
    compileSdkVersion = 15
    buildToolsVersion = '24.0.1'
    targetSdkVersion = 15
    minSdkVersion = 15
    versionCode = 28
    versionName = "0.3.2"
}
```

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Do not work ! Still Permission denied.

**Comment by duanhong169** [comment]
Still Permission denied when using input file from external storage

> onFailure: ffmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
>                                                                           built with gcc 4.8 (GCC)
>                                                                           configuration: --target-os=linux --cross-prefix=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/vagrant/SourceCode/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/vagrant/SourceCode/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
>                                                                           libavutil      55. 17.103 / 55. 17.103
>                                                                           libavcodec     57. 24.102 / 57. 24.102
>                                                                           libavformat    57. 25.100 / 57. 25.100
>                                                                           libavdevice    57.  0.101 / 57.  0.101
>                                                                           libavfilter     6. 31.100 /  6. 31.100
>                                                                           libswscale      4.  0.100 /  4.  0.100
>                                                                           libswresample   2.  0.101 /  2.  0.101
>                                                                           libpostproc    54.  0.100 / 54.  0.100
>                                                                         /storage/emulated/0/audio/Fade_AlanWalker.mp3: Permission denied

**Comment by duanhong169** [comment]
Found the reason, when Android version is 6.0 or above, the permission of external storage must be explicitly granted by user.

**Comment by Aditya94A** [comment]
@duanhong169 What exactly did you do to solve this?

Since this library doesn't work if we set it to targetSdk to >23, I have it at 22. But since I have it at 22

```
 ActivityCompat.requestPermissions(MainActivity.this,
                new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
``` 

Doesn't seem to do anything on Android 6.0+. So, now I'm stuck. If I upgrade targetSdk to over 22, my app will simply stop working on 6.0+, but since I can't change the targetSdk, I can't seem to get WRITE_EXTERNAL permission, meaning that my app can't write to the SD card

How exactly did you solve this?

**Comment by deepakkumardk** [comment]
Any fix on this issue?
