### ISSUE TITLE
encoder 'aac' not enable exception while processing video for slowing

### ISSUE THREAD

**Issue by amna-mirza** [hiteshsondhi88/ffmpeg-android-java#106]
[aac @ 0x416c26f0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

**Comment by iamluodong** [comment]
You can add -strict -2 solve this problem.

ffmpeg -i xxx.mp4 -c:a aac -ar 44100 -b:a 128k -strict -2
