### ISSUE TITLE
Run ffmpeg command in android device getting error No such filter:" Error initializing complex filter

### ISSUE THREAD

**Issue by iharshb** [hiteshsondhi88/ffmpeg-android-java#111]
I am used  FFmpeg command that have complex filter . Now at a time for running command   its show    filter error  [AVFilterGraph @ 0xb8.......] No such filter "  
Error  initalizing complex filters . Invalid argument :

Check if i m wrong in this converting in String array :
video1_path=  my video path in device 

String[] cr={" -i "+video1_path," -i "+video1_path," -i "+video1_path," -i "+video1_path," -i "+video1_path," -filter_complex "," [0:v]setpts=PTS-STARTPTS[1];"," [1:v]format=yuva420p,fade=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+(4/TB)[2];"," [2:v]format=yuva420p,fade=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+(8/TB)[3];"," [3:v]format=yuva420p,fade=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+(12/TB)[4];"," [4:v]format=yuva420p,fade=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+(16/TB)[5];"," [1][2]overlay[12];"," [12][3]overlay[123];"," [123][4]overlay[1234];"," [1234][5]overlay,format=yuv420p[v]"," -map [v]"," /sdcardresult.mp4"};

**Comment by adancygier** [comment]
what was the solution to this problem?
