### ISSUE TITLE
unable to find a suitable output format for ":invalid argument

### ISSUE THREAD

**Issue by metinilhan** [hiteshsondhi88/ffmpeg-android-java#116]
I got that error when I try to run following command
"-i /storage/emulated/0/video.mp4  -vf scale=320:240/storage/emulated/0/video_ffmpegresult.mp4

**Comment by Pirksy** [comment]
"-i /storage/emulated/0/video.mp4 -vf scale=320:240 -y /storage/emulated/0/video_ffmpegresult.mp4"
