### ISSUE TITLE
Error initializing complex filters

### ISSUE THREAD

**Issue by dpproduction** [hiteshsondhi88/ffmpeg-android-java#118]
Hi guys, great work!
I try to execute this command: 
-i /storage/emulated/0/prepared/bg.jpeg -i /storage/emulated/0/prepared/test_%d.png -filter_complex \"[0][1]overlay=5:H-h-5[b];[b] drawtext=fontfile=/storage/emulated/0/prepared/Roboto-Light.ttf::text=Test :fontsize=46:fontcolor=blue:x=w-tw-10:y=h-th-10\" -shortest testvid.mp4

It works on my Ubuntu, but on android I get 
No such filter: '"'
07-13 15:15:16.725 15605-15605/com.github.hiteshsondhi88.sampleffmpeg D/Home:  Started command : ffmpeg Error initializing complex filters.
07-13 15:15:16.726 15605-15605/com.github.hiteshsondhi88.sampleffmpeg D/Home:  Started command : ffmpeg Invalid argument

I try use ' instead \" , adding separate to \" [0] [1] overlay=5:H-h-5 [b] ; [b] drawtext=fontfile=/storage/emulated/0/prepared/Roboto-Light.ttf::text=Test  :fontsize=46:fontcolor=blue:x=w-tw-10:y=h-th-10\" 
but it did't work.

Please, help me.

**Comment by dpproduction** [comment]
I found solution!
Just need to remove quotes and spaces.

**Comment by MythodeaLoL** [comment]
Thanks for sharing the solution **=)**
_Now you can close issue_ :+1:

**Comment by taitran2008** [comment]
"Remove quotes and spaces"? Could you write down the code after fixing ? I have the same issue ;(
`No such filter: '"'
Error initializing complex filters`

**Comment by dpproduction** [comment]
>I have the same issue

Share your code

**Comment by satyakirand** [comment]
i have the same issue. please help me.here is my code

/usr/bin/ffmpeg -loop 1 -framerate 25 -t 3 -i /home/sys017/NetBeansProjects/test/web/videoimagefiles/video_2.png -t 3 -f lavfi -i aevalsrc=0 -i /home/sys017/NetBeansProjects/test/web/videoimagefiles/vimage_22017/v3.mp4 -v debug -strict -2 -filter_complex [0:0]fade=out:st=50:d=25:alpha=1[title];[title][1:0][2:0][2:1] concat=n=2:v=1:a=1 /home/sys017/NetBeansProjects/test/web/videoimagefiles/vimage_22017/1487048304222_mod.mp4



could you please help me.

**Comment by sashatinkoff** [comment]
@satyakirand have been able to solve the problem?

**Comment by IstrateAndrei** [comment]
Hi, i've got the same issue: "No such filter: '' ".I've got stuck on this for days, please if someone can help.
The code runs ok in command line, the problem is when i try to run it in Android(And yes, i removed all the quotes and spaces).
Here is the code:

-i video1.mp4 -i video2.mp4 -f lavfi -i color=black -filter_complex 
[0:v]format=pix_fmts=yuva420p,fade=t=out:st=8:d=1:alpha=1,setpts=PTS-STARTPTS[va0];
[1:v]format=pix_fmts=yuva420p,fade=t=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+6/TB[va1];
[2:v]scale=1080x720,trim=duration=9[over];[over][va0]overlay[over1];[over1][va1]overlay[outv]
 -vcodec libx264 -map [outv]  output.mp4

**Comment by sagartrehan** [comment]
@IstrateAndre Did you get the solution?

**Comment by MudassirAsghar22** [comment]
Error: no such filter: Error initializing complex filters. invalid argument.
i am using following command;
 "-i /storage/emulated/0/DCIM/Camera/VID_20180528_085108.mp4 -i /storage/emulated/0/DCIM/Camera/VID_20180528_085121.mp4 \\\n" +
                        " -filter_complex \"[1:v]setpts=PTS-10/TB[a]; \\\n" +
                        "                 [0:v][a]overlay=enable=gte(t\\,5):shortest=1[out]\" \\\n" +
                        "-map [out] -map 0:a \\\n" +
                        "-c:v libx264 -crf 18 -pix_fmt yuv420p \\\n" +
                        "-c:a copy \\\n" +
                        "/storage/emulated/0/DCIM/Camera/VID_20180528_033212.mp4"

**Comment by liangzs** [comment]
> Hi, i've got the same issue: "No such filter: '' ".I've got stuck on this for days, please if someone can help.
> The code runs ok in command line, the problem is when i try to run it in Android(And yes, i removed all the quotes and spaces).
> Here is the code:
> 
> -i video1.mp4 -i video2.mp4 -f lavfi -i color=black -filter_complex
> [0:v]format=pix_fmts=yuva420p,fade=t=out:st=8:d=1:alpha=1,setpts=PTS-STARTPTS[va0];
> [1:v]format=pix_fmts=yuva420p,fade=t=in:st=0:d=1:alpha=1,setpts=PTS-STARTPTS+6/TB[va1];
> [2:v]scale=1080x720,trim=duration=9[over];[over][va0]overlay[over1];[over1][va1]overlay[outv]
> -vcodec libx264 -map [outv] output.mp4

hi, had you solved it,I met the same problem too

**Comment by liangzs** [comment]
it's work,i solve my problem

**Comment by sashatinkoff** [comment]
> it's work,i solve my problem

Hey, if you have solved a problem please share your solution

**Comment by liangzs** [comment]
> > it's work,i solve my problem
> 
> Hey, if you have solved a problem please share your solution

en, remove quotes and spaces then success,，my mistake is that my code has a place with two spaces

**Comment by devt23** [comment]
I have same problem for reverse video command.Please help me out.

ffmpeg-y-i/storage/emulated/0/Editor/VideoTrim/VideoTrim_134850.mp4-filter_complex[0:v]reverse[v];[0:a]areverse[a]-map[v]-map[a],[0:v]reverse[v];[0:a]areverse[a]-map[v]-map[a]-presetsuperfast/storage/emulated/0/Editor/VideoEdit/1613031543160.mp4


AVLOG: [AVFilterGraph @ 0x7e1f17efe0] Unable to parse graph description substring: "-map[v]-map[a],[0:v]reverse[v];[0:a]areverse[a]-map[v]-map[a]"
AVLOG: Error initializing complex filters.
AVLOG: Invalid argument
