### ISSUE TITLE
What is the minSdkVersion to use lib and why?

### ISSUE THREAD

**Issue by ahmashour1** [hiteshsondhi88/ffmpeg-android-java#13]
Hi Mr.Hitesh,
First thank you for this wonderful library, then I have question about what is the  minSdkVersion to use Lib ? 
as I see in main example the  minSdkVersion is 16Api but in the Lib it selfe it whas 14Api, So what is the true  minSdkVersion?
And what is api used need this  minSdkVersion so if I can search to support old api.
Thanks

**Comment by kolipass** [comment]
Look #2 
>To support older devices you need to recompile the binaries yourself using

**Comment by hiteshsondhi88** [comment]
Thanks @kolipass
