### ISSUE TITLE
Execute onFailure called on a specific device

### ISSUE THREAD

**Issue by pang0018** [hiteshsondhi88/ffmpeg-android-java#14]
I downloaded your sample apk and it works fine on all my devices except one. I am not sure where to begin with this error and how to work around it, can you read the following about and tell me why FFMpef may not work on this specific device. It a Version Ellipsis 8 tablet if that helps.

02-20 20:10:58.435    6732-6732/com.mytestapp.video D/App Message﹕ onFailure - WARNING: linker: /data/data/com.mytestapp.video/files/ffmpeg has text relocations. This is wasting memory and is a security risk. Please fix.
    ffmpeg version n2.4.2 Copyright (c) 2000-2014 the FFmpeg developers
    built on Oct  7 2014 15:08:46 with gcc 4.8 (GCC)
    configuration: --target-os=linux --cross-prefix=/home/sb/Source-Code/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/home/sb/Source-Code/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/sb/Source-Code/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/sb/Source-Code/ffmpeg-android/build/armeabi-v7a-neon --extra-cflags='-I/home/sb/Source-Code/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -mfpu=neon' --extra-ldflags='-L/home/sb/Source-Code/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
    libavutil      54.  7.100 / 54.  7.100
    libavcodec     56.  1.100 / 56.  1.100
    libavformat    56.  4.101 / 56.  4.101
    libavdevice    56.  0.100 / 56.  0.100
    libavfilter     5.  1.100 /  5.  1.100
    libswscale      3.  0.100 /  3.  0.100
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  0.100 / 53.  0.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/VID_20150217_163840.3gp':
    Metadata:
    major_brand     : 3gp4
    minor_version   : 0
    compatible_brands: isom3gp4
    creation_time   : 2015-02-17 22:38:53
    Duration: 00:00:11.13, start: 0.000000, bitrate: 12411 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 12108 kb/s, SAR 65536:65536 DAR 16:9, 29.03 fps, 30.17 tbr, 90k tbn, 180k tbc (default)
    Metadata:
    rotate          : 90
    creation_time   : 2015-02-17 22:38:53
    handler_name    : VideoHandle
    Side data:
    displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: amr_nb (samr / 0x726D6173), 8000 Hz, mono, flt, 12 kb/s (default)
    Metadata:
    creation_time   : 2015-02-17 22:38:53
    handler_name    : SoundHandle
    [libx264 @ 0x42107d50] using SAR=1/1
    [libx264 @ 0x42107d50] using cpu capabilities: none!
    [libx264 @ 0x42107d50] profile Constrained Baseline, level 4.2
    [libx264 @ 0x42107d50] 264 - core 142 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
    [aac @ 0x42108c80] Too many bits per frame requested
    Output #0, mp4, to '/storage/emulated/0/Pictures/OLNVideoUploader/VID_20150220_201057.mp4':
    Metadata:
    major_brand     : 3gp4
    minor_version   : 0
    compatible_brands: isom3gp4
    Stream #0:0(eng): Video: h264 (libx264), yuv420p, 1920x1080 [SAR 65536:65536 DAR 16:9], q=-1--1, 30.17 fps, 30.17 tbn, 30.17 tbc (default)
    Metadata:
    rotate          : 90
    creation_time   : 2015-02-17 22:38:53
    handler_name    : VideoHandle
    encoder         : Lavc56.1.100 libx264
    Stream #0:1(eng): Audio: aac, 0 channels, 128 kb/s (default)
    Metadata:
    creation_time   : 2015-02-17 22:38:53
    handler_name    : SoundHandle
    encoder         : Lavc56.1.100 aac
    Stream mapping:
    Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
    Stream #0:1 ->
02-20 20:10:58.435    6732-6732/com.mytestapp.video D/App Message﹕ onFinish

**Comment by shanrais** [comment]
I am also having the same issue.
This issue is replicated in devices having IceCreamSandwich OS,

I am facing this error :
'libcore.io.errnoexception: kill failed: esrch (no such process)'
Link : https://www.google.com.pk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=libcore.io.errnoexception%3a%20kill%20failed%3a%20esrch%20(no%20such%20process)

**Comment by hiteshsondhi88** [comment]
This issue is invalid as current version of app only supports JB+ devices.

Closed.

**Comment by mtst99** [comment]
Hi and thanks for your great job.
My conversion speed is very low and I can't see any activity on cpu although my phone gets hot.
"-ss 00:10:00 -i "+VideoIn+" -to 00:01:00 -strict -2 -c:v libx264 -preset ultrafast -qp 0 -c:a aac -b:a 192k "+VideoOut+" -y"
I've got this two line of texts which I need help about.
WARNING: linker: /data/data/com.videoeditor.me.myapp/files/ffmpeg has text relocations. This is wasting memory and is a security risk. Please fix.
using cpu capabilities: none!
I'm using your latest version 2.5 and I grabbed it with gradle.
Phone -> Galaxy s5 sm-g900h
