### ISSUE TITLE
How to execute FFprobe ?

### ISSUE THREAD

**Issue by Rasoul-Ghadiri** [hiteshsondhi88/ffmpeg-android-java#145]
hi,
I've tried to run ffbrobe but it is not possible. why?
At the first of compiling the log has this message:  --disable-ffprobe.
how can I enable ffprobe?

**Comment by ruha9005** [comment]
@Rasoul-Ghadiri you can't enable it in this build (Issue: https://github.com/WritingMinds/ffmpeg-android-java/issues/51). But you can recompile ffmpeg sources by yourself

**Comment by olegazyx** [comment]
Sorry, if I advertise mine repository, may be you try MediaInfo

**Comment by Rasoul-Ghadiri** [comment]
@ruha9005 @OLEG4120 Thanks for your replies.
