### ISSUE TITLE
when using subtitles filter, there is such error, and the subtitle is not showing 

### ISSUE THREAD

**Issue by JunfeiW** [hiteshsondhi88/ffmpeg-android-java#158]
D/FFmpegManager: onProgress: Fontconfig error: Cannot load default config file
D/FFmpegManager: onProgress: [Parsed_subtitles_0 @ 0xacae8f30] No usable fontconfig configuration file found, using fallback.
D/FFmpegManager: onProgress: Fontconfig error: Cannot load default config file
D/FFmpegManager: onProgress: [Parsed_subtitles_0 @ 0xacae8f30] No valid fontconfig configuration found!
D/FFmpegManager: onProgress: [Parsed_subtitles_0 @ 0xacae8f30] can't find selected font provider

**Comment by douglasfeitosa** [comment]
@JunfeiW I have the same error. What is the solution?

**Comment by wanghaihui** [comment]
I have the same error, and not show the subtitles, can you help me?
