### ISSUE TITLE
Convert mp4 to mp3 command not working

### ISSUE THREAD

**Issue by hubino** [hiteshsondhi88/ffmpeg-android-java#18]
**separate video from video**
Thanks for your useful library.I need to separate `video(not contains audio)` from `input video(contains audio)` file so I used this command 
`ffmpeg -i input.mkv -map 0:v -codec copy output.mkv` in Home.java
  `String command = "-i "+Environment.getExternalStorageDirectory()+"/RampTest/input.mp4"
                           +" -map 0:v -codec copy "+Environment.getExternalStorageDirectory()+"/RampTest/output.mp4";`
`execFFmpegBinary(command);`
this command worked successfully and created a `output.mp4` file in `RampTest` directory

**separate audio from video**
`ffmpeg -i input.mp4 output.mp3`
or
`ffmpeg -i input.mp4 -b:a 192K -vn output.mp3`
I got the desired output from above two commands while using in my `windows` machine `command prompt`.
but when I used these commands in my code it created a `empty file(0kb)` with the name `output.mp3` 

 `String command = "-i "+Environment.getExternalStorageDirectory()+"/RampTest/input.mp4 "+
                            " -b:a 192K -vn "+Environment.getExternalStorageDirectory()+"/RampTest/output.mp3";`
`execFFmpegBinary(command);`

**Comment by hiteshsondhi88** [comment]
Hey hubino,

Current version of this library does not have binaries which supports libmp3lame (required for mp3). To do above you need to use custom ffmpeg binaries compiled from this branch -> https://github.com/hiteshsondhi88/ffmpeg-android/tree/feature/feature-libmp3

Please note that libmp3lame feature of ffmpeg still needs testing.

**Comment by hubino** [comment]
Oh, okay thanks

**Comment by hubino** [comment]
So I need to use https://github.com/hiteshsondhi88/ffmpeg-android/tree/feature/feature-libmp3 this source of code to build a `binary` and then have to use in my code.

is it any possible for using this built binary in your library(https://github.com/hiteshsondhi88/ffmpeg-android-java)

**Comment by hiteshsondhi88** [comment]
Yes you can use the above binary in the code by just replacing the binaries and changing the corresponding shasum of the binary.

**Comment by prateeksethi002** [comment]
Hi hiteshsondhi88,

I am trying to create an mp3 file by combining two audio files referring to https://github.com/WritingMinds/ffmpeg-android-java
But I was getting the error that the Encoder(codec mp3) not found. And I used below link to get some help.But it opened into 404 page not found.
https://github.com/hiteshsondhi88/ffmpeg-android/tree/feature/feature-libmp3.
So can you help in getting me a ffmpeg binary which has mp3 support(I think its libmp3lame library).
Thanks in advance.
