### ISSUE TITLE
never return

### ISSUE THREAD

**Issue by tcking** [hiteshsondhi88/ffmpeg-android-java#236]
the commond is like: `ffmpeg -i /sdcard/test.mp4 -vcodec libx264 -b:v 2073600 /sdcard/test2.mp4`
after execute,the `onProgress` print some log,but `onSuccess` ,`onFailure` never called (cpu usage 0%)，no more log out.

![image](https://user-images.githubusercontent.com/2508474/30430609-51d1862c-998e-11e7-972e-1f41311658dd.png)

**Comment by MrLepage** [comment]
I have this problem if the output file already exists.

**Comment by MrLepage** [comment]
I need to add "-y" to the command.
It overwrites output files without asking.

**Comment by tcking** [comment]
you have solved my problem,thanks for your sharing @UNCVR
