### ISSUE TITLE
jpg thumbnail wrongly rotated

### ISSUE THREAD

**Issue by dayeba** [hiteshsondhi88/ffmpeg-android-java#24]
I'm trying to generate a cover image for a video using ffmpeg, my command is **ffmpeg -i input.mp4 -ss 0 -vframes 1 out.jpg**, this command works fine but in some cases the generated image gets a wrong rotation, rotated 90 degrees clock wise to be exact. It happens for all the portrait videos I've tried. The same command works without any issue in windows command line for the same videos. Can someone give a hint on how to solve this?

**Comment by hiteshsondhi88** [comment]
@dayeba Github is for issues not for FFmpeg support and you should have asked this on SO first.

But here is the command which you can try -
ffmpeg -i input.mp4 -ss 0 -vframes 1 -vf transpose=1 out.jpg
