### ISSUE TITLE
How to use this app in eclipse?

### ISSUE THREAD

**Issue by shaileshmulange** [hiteshsondhi88/ffmpeg-android-java#26]
Hi Sorry for this issue, this not issue but I want some help from your side can you tell me how to use this app in eclipse. I have tried this for eclipse but getting an error i.e.
Caused by: java.lang.IllegalStateException: Module adapter for class com.github.hiteshsondhi88.sampleffmpeg.DaggerDependencyModule could not be loaded. Please ensure that code generation was run for this module.

**Comment by hiteshsondhi88** [comment]
Hi @shaileshmulange 

This issue is meant for stackoverflow not here. On the support towards eclipse, you can download the yaar from the gradle manually and import that aar to eclipse project.

**Comment by shaileshmulange** [comment]
Hi @hiteshsondhi88 
I have followed below steps for use(import) aar file in eclipse project i.e.
The AAR file consists of a JAR file and some resource files. Here are the steps to convert:

Extract the AAR file using standard zip extract
Find the classes.jar file in the extracted files
Rename it to your liking and use the wanted jar file in your project

but I have getting following error.
06-22 10:14:58.673: E/AndroidRuntime(6585): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.hiteshsondhi88.sampleffmpeg/com.github.hiteshsondhi88.sampleffmpeg.Home}: java.lang.IllegalStateException: Module adapter for class com.github.hiteshsondhi88.sampleffmpeg.DaggerDependencyModule could not be loaded. Please ensure that code generation was run for this module.
