### ISSUE TITLE
rtmp secure token aways loading

### ISSUE THREAD

**Issue by MelissaTaylor** [hiteshsondhi88/ffmpeg-android-java#27]
I cant play with rtmpdump+ffmpeg rtmp://... secure token **-t SDfg451fdg**, please help me.

**Comment by hiteshsondhi88** [comment]
Hi @MelissaTaylor

This library doesn't support rtmp yet.

**Comment by MelissaTaylor** [comment]
ok i'm waiting for a future release, tks
