### ISSUE TITLE
How to update FFMPEG Version

### ISSUE THREAD

**Issue by ejdelros08** [hiteshsondhi88/ffmpeg-android-java#29]
Hi, I'm sorry for this issue but can anyone help me and teach me how to update the ffmpeg version of this library? I'm using Android studio 1.2.2 running on Ubuntu 14.04 LTS. As i'm using this library, the current version logged on my logcat is 2.4, but as of now, the version of ffmpeg is 2.7, i just need to update my ffmpeg because i need to use the '-noautorotate' option. Thank you very much!

**Comment by ejdelros08** [comment]
I'm sorry, I've already resolved my issue. I guess i'll just close this one. Thank you

**Comment by gouravd** [comment]
Could you please share the steps?

**Comment by chodison** [comment]
@ejdelros08 where is the ffmpeg library ?
