### ISSUE TITLE
Can ffmpeg commands be canceled

### ISSUE THREAD

**Issue by tspecht** [hiteshsondhi88/ffmpeg-android-java#3]
Hey,

I tried cancelling my ffmpeg command in onDestory but the kill function provided is not working, any suggestions?

**Comment by Shahar2k5** [comment]
code still contains the && operator... :(

**Comment by andrewcross** [comment]
It looks like the && operator fix is in master, but not in the 0.2.5 build available via gradle

**Comment by sam7700** [comment]
as on March 2016 is still the same on the gradle build and the aar linked in the main site, I think we can pretty much consider this not maintained anymore...
