### ISSUE TITLE
Tried to create mp4 from images in sdcard

### ISSUE THREAD

**Issue by jahangirkabir** [hiteshsondhi88/ffmpeg-android-java#30]
i have tried this 
-r 1/5 -i /sdcard/DP/clock%03d.jpg -c:v libx264 -r 30 -pix_fmt yuv420p show.mp4
-r 1 -i /sdcard/DP/clock%03d.jpg show.mp4

This create mp4 file but why this is 0 byte in size ?
What is the error?

**Comment by hiteshsondhi88** [comment]
Please use SO for such questions, this is not the library issue.
