### ISSUE TITLE
Combile Audio and Video 

### ISSUE THREAD

**Issue by GauravCreed** [hiteshsondhi88/ffmpeg-android-java#309]
Can i create video from audio + video (With no sound)

i hava video with no sound (1sec size), and audio (0.30sec) i want to combile and create new video as length of audio(0.30)

` String cmd[] = { "-i", newAudioPath, "-i", pathtoVideo, "-c", "copy", outputVideo};`

**Comment by monxarat** [comment]
You can be using with param `shortest`

**Comment by GauravCreed** [comment]
can u please guide me how it's possible ?

**Comment by yadavkohi** [comment]
you can combine audio with video by following command:
-i audio.mp3 -i video.mp4 -map 0:v:0 -map 1:a:0 -y -acodec copy -vcodec copy output.mp4

if you want fast processing then use the below one
-i audio.mp3 -i video.mp4 -map 0:v:0 -map 1:a:0 -y -acodec copy -vcodec copy -preset ultrafast -async 1 output.mp4

**Comment by GauravCreed** [comment]
Thanks @yadavkohi 

it's great work, now working....

**Comment by yadavkohi** [comment]
please close the issue if the answer satisfy your requirement

**Comment by nacartunahan** [comment]
Yadavhohi said that;
you can combine audio with video by following command:
-i audio.mp3 -i video.mp4 -map 0✌️0 -map 1🅰️0 -y -acodec copy -vcodec copy output.mp4

how can we write this in Java like String command[ ] = {" " };

String cmd[] = { "-i", audioPath, "-i", currentVideo.getVideoURL(), "-y", "-acodec copy", "-vcodec copy", "final.mp4"}; is this true for just merging video and audio
