### ISSUE TITLE
Can't add lib aar to my project

### ISSUE THREAD

**Issue by Edig** [hiteshsondhi88/ffmpeg-android-java#32]
Hi,

I try to add ffmpeg to my project without success. I download the AAR lib and add it to my folder app/libs, after that I add to my app/build.gradle

```

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile(name:'FFmpegAndroid', ext:'aar')
}

```

But when I try to import FFMPEG or use the code it doesn't let, like if i never add it before, any ideas on what I'm doing wrong?

Best,

**Comment by magicomiralles** [comment]
Hi, are you sure that you added these blocks to
*build.gradle(Module: app)*
and not to
*build.gradle(Project: appName)*

These imports worked for me:
```java
import com.github.hiteshsondhi88.libffmpeg.FFmpeg;
import com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteResponseHandler;
import com.github.hiteshsondhi88.libffmpeg.LoadBinaryResponseHandler;
import com.github.hiteshsondhi88.libffmpeg.exceptions.FFmpegCommandAlreadyRunningException;
import com.github.hiteshsondhi88.libffmpeg.exceptions.FFmpegNotSupportedException;
```

I hope this helps.

**Comment by Edig** [comment]
Hi magic, thanks but was my bad

the error is that the library I download has a different name

```
dependencies {
    compile(name:'FFmpegAndroid-0.2.5', ext:'aar')
}
```

**Comment by magicomiralles** [comment]
I don't know how I didn't see it, It happened to me too when I used it for the first time.
