### ISSUE TITLE
Merge audio and video

### ISSUE THREAD

**Issue by yadavkohi** [hiteshsondhi88/ffmpeg-android-java#321]
Does anybody know how to merge audio and video and make a final video which is having the audio (audio file audio as well as video file audio).

I have tried some map option to keep video all streams and keep audio only audio stream but it will not work.

**Comment by yadavkohi** [comment]
I have got the single command to merge 2 audio with one video file:
-i sample_video.mp4 -i sample_audio1.mp3 -i sample_audio2.mp3 -filter_complex [1][2]amix=inputs=2[a] -map 0:v -map [a] -c:v copy Output.mp4


it did not require to first extract audio from video, then merger this extracted audio with audio 2 and them finally merge video with the merged audio. In just single command we can merge 2 audio and one video

**Comment by nacartunahan** [comment]
How can I write this command in Android Studio. I need to write this command like this String commmand[] = {" ", " "};
