### ISSUE TITLE
How to add a subtitle to the video

### ISSUE THREAD

**Issue by lightlz** [hiteshsondhi88/ffmpeg-android-java#36]
I am trying to add subtitles to the video using this lib.
I've already seen this :
http://stackoverflow.com/questions/8672809/use-ffmpeg-to-add-text-subtitles
https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo

I was able to output .mp4/.avi files,but I can't see the subtitles in the video.

**Comment by hiteshsondhi88** [comment]
You can use libass while burning subtitles in the video, but you need to create the custom fontconfig too and use that for burning subtitles

This is not a library issue so Closing this, please use SO for such questions
