### ISSUE TITLE
Not Working on Android api target  29

### ISSUE THREAD

**Issue by manish-jet** [hiteshsondhi88/ffmpeg-android-java#362]
Can Anyone please help me with target 29 as it is working in 28 target api

**Comment by vaibhav-droid** [comment]
Have you got any solution as i am facing issue while using it on target 29

**Comment by krushnarathod** [comment]
1nikolas:master

**Comment by krushnarathod** [comment]
https://github.com/1nikolas/ffmpeg-android-java try this one

**Comment by vaibhav-droid** [comment]
> https://github.com/1nikolas/ffmpeg-android-java try this one

@krushnarathod I have tries this lib but getting unsupported version error and ffmpeg loading is getting failed. Can you please share more insights on this

**Comment by krushnarathod** [comment]
static String getFFmpeg(Context context) {


        return context.getApplicationInfo().nativeLibraryDir + "/" + ffmpegFileName;
    }

change this method in com.github.hiteshsondhi88.libffmpeg.FileUtils.java
