### ISSUE TITLE
 Unable to find a suitable output format for 'ffmpeg'

### ISSUE THREAD

**Issue by Anmol92verma** [hiteshsondhi88/ffmpeg-android-java#43]
command is﹕ ffmpeg -i /storage/sdcard0/ptlinkx/2ada2463-0f81-4b0e-b3b1-711df7428552.mp4 -vcodec mpeg4 /storage/sdcard0/2ada2463-0f81-4b0e-b3b1-711df7428552.mp4 what could be wrong ?

**Comment by dominicthomas** [comment]
If the input file is a .mp4 you can just use -vcodec copy or -c:v copy or -c copy instead of specifying the output format?

**Comment by hanappaula** [comment]
You don't have to use "ffmpeg" in the beginning of the command. You only have to do like this "-i /storage/sdcard0/ptlinkx/2ada2463-0f81-4b0e-b3b1-711df7428552.mp4 -vcodec mpeg4 /storage/sdcard0/2ada2463-0f81-4b0e-b3b1-711df7428552.mp4".

**Comment by Anmol92verma** [comment]
Thanks @hanappaula i figured it out, its working like charm now , :+1:

**Comment by pouyanzm** [comment]
Thanks @hanappaula is right ... :)

**Comment by suneelt68** [comment]
thanku @hanappaula
