### ISSUE TITLE
Create mp4 from pictures

### ISSUE THREAD

**Issue by sashatinkoff** [hiteshsondhi88/ffmpeg-android-java#8]
I tried to create video file from set of images, but couldn't do it. I use following code to do it

ffmpeg -i /storage/emulated/0/Pictures/khello/image_%4d.jpg -vcodec mpeg4 /storage/emulated/0/Pictures/khello/test.avi

What I see in log

 ffmpeg version n2.4.2 Copyright (c) 2000-2014 the FFmpeg developers
    built on Oct  7 2014 15:08:46 with gcc 4.8 (GCC)
    configuration: --target-os=linux --cross-prefix=/home/sb/Source-Code/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/home/sb/Source-Code/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/sb/Source-Code/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/sb/Source-Code/ffmpeg-android/build/armeabi-v7a-neon --extra-cflags='-I/home/sb/Source-Code/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all -mfpu=neon' --extra-ldflags='-L/home/sb/Source-Code/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
    libavutil      54.  7.100 / 54.  7.100
    libavcodec     56.  1.100 / 56.  1.100
    libavformat    56.  4.101 / 56.  4.101
    libavdevice    56.  0.100 / 56.  0.100
    libavfilter     5.  1.100 /  5.  1.100
    libswscale      3.  0.100 /  3.  0.100
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  0.100 / 53.  0.100
    Input #0, image2, from '/storage/emulated/0/Pictures/DAILY/khello/image_%4d.jpg':
    Duration: 00:00:00.40, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg), 768x1280 [SAR 1:1 DAR 3:5], 25 fps, 25 tbr, 25 tbn, 25 tbc
    [NULL @ 0xb5e60a00] Unable to find a suitable output format for 'ffmpeg'
    ffmpeg: Invalid argument

The same code created video successfully on my mac

What I do wrong??

**Comment by hiteshsondhi88** [comment]
You cannot convert to avi this library doesn't have the necessary codec for avi yet. However you can set mp4 as output video.

**Comment by DhavalSpaceO** [comment]
Hello Hitesh,

I am using below command in Android application but its showing below error.

ffmpeg -framerate 1/5 -i /storage/emulated/0/Download/ffmpeg%01d.jpg -c:v libx264 -r 30 -pix_fmt yuv420p /storage/emulated/0/Download/out.mp4

Input #0, image2, from '/storage/emulated/0/Download/ffmpeg1.jpg':
Duration: 00:00:00.04, start: 0.000000, bitrate: 9644 kb/s
Stream #0:0: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 500x500 [SAR 96:96 DAR 1:1], 25 fps, 25 tbr, 25 tbn, 25 tbc
[NULL @ 0xb5bdc600] Unable to find a suitable output format for 'ffmpeg'
ffmpeg: Invalid argument

**Comment by sashatinkoff** [comment]
DhavalSpaceO, you shouldn't use "ffmpeg" in the beginning of command string. Try this command 
"-framerate 1/5 -i /storage/emulated/0/Download/ffmpeg%01d.jpg -c:v libx264 -r 30 -pix_fmt yuv420p /storage/emulated/0/Download/out.mp4"

**Comment by DhavalSpaceO** [comment]
@sashatinkoff Thanks.

Its working fine now. Do you know how to apply animation in video?

**Comment by DhavalSpaceO** [comment]
Hello Hitesh,

I am trying to apply fade in and out animation to all image slides. I am using below command for same.

-loop 1 -t 5 -i /storage/emulated/0/Download/ffmpeg1.jpg 
-loop 1 -t 5 -i /storage/emulated/0/Download/ffmpeg2.jpg 
-loop 1 -t 5 -i /storage/emulated/0/Download/ffmpeg3.jpg 
-filter_complex 
'[0:v]fade=t=out:st=4:d=1[v0]; 
[1:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v1]; 
[2:v]fade=t=in:st=0:d=1,fade=t=out:st=4:d=1[v2];
[v0][v1][v2]concat=n=3:v=1:a=0,format=yuv420p[v]' -map '[v]' 
/storage/emulated/0/Download/out.mp4

While executing above command, i am getting below error.

No such filter: '[0:v]fade=t=out:st=4:d=1[v0];' Error initializing complex filters.

**Comment by Nehachaudhary0727** [comment]
@DhavalSpaceO have you resolved animation issue?

**Comment by mansiJspaceo** [comment]
Hello i have also facing issue in add Animation between multiple Images.
  i am using this library **https://github.com/tanersener/ffmpeg-video-slideshow-scripts** for animation.

anybody know how to convert .sh to FFMPEG command.
